version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
