version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-performance
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: git submodule init
      - run: git submodule update
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
      - run: .circleci/create_benchmark.sh
      - save_cache:
          key: v1-performance
          paths:
            - ~/performance
      - run: mix test
      - restore_cache:
          keys:
            - v1-plt-cache-{{ checksum "mix.lock" }}
            - v1-plt-cache
      - run: mix dialyzer --plt
      - save_cache:
          key: v1-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix
      - run: mix dialyzer --halt-exit-status
      - store_test_results:
          path: _build/test/lib/locale_names
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
